### ISSUE TITLE
Dropdown - control over disabled items

### ISSUE THREAD

**Issue by alina-lapina** [statisticsnorway/ssb-component-library#179]
**Is your feature request related to a problem? Please describe.**
I use your library in a SSB react-project. Some options in a dropdown have to be disabled.

**Describe the solution you'd like**
Property items could take objects with `(string) title`, `(string) id`, and `**(boolean) disabled**`.

**Describe why this is useful for SSB**
In my case SSB sections (divisions) have to be selected in a Dropdown. When a section is outdated but already saved, it stil have to be shown, but it should not be possible to choose it for new objects.

**Additional context**
Proof of consept app is running here [subsets-client](https://subsets-web.staging-bip-app.ssb.no/create)

**Comment by ssb-cgn** [comment]
Solved in  https://github.com/statisticsnorway/ssb-component-library/releases/tag/2.0.10
