### ISSUE TITLE
Dropdown - keyboard compatibility

### ISSUE THREAD

**Issue by alina-lapina** [statisticsnorway/ssb-component-library#180]
**Is your feature request related to a problem? Please describe.**
It is not possible to navigate between options in a Dropbox using keyboard. Bad usability and user experience.

**Describe the solution you'd like**
Instead of <input> use <select> and <options> or listen for key press events

**Describe why this is useful for SSB**
SSB has to be WCAG compliant

**Additional context**
-

**Comment by ssb-cgn** [comment]
Solved in https://github.com/statisticsnorway/ssb-component-library/releases/tag/2.0.10

**Comment by prabu-ssb** [comment]
The following keybindings are now available --

**Normal dropdown**
- `ENTER` - opens the dropdown (if it is closed) or selects currently active list item (if open)
- `ESCAPE` - closes the dropdown (if it is open), currently active list item is cleared
- `UP`/`DOWN` arrows - navigate up/down the list items. (Note: we have a known caveat here - that the item one navigates to using the arrow keys is scrolled to, even if it is already in the viewport).
- `TAB` into or out of the dropdown component (`SHIFT`+ `TAB` works in the reverse direction)
- `SPACE` - opens or closes the dropdown - does not affect selection (inherits default browser behaviour)

**Searchable dropdown** - extends the normal behaviour above with
- `TAB` - a second tab focuses into the searchable input field. Every keypress attempts to narrow the available options.
- `SPACE` - when inside the search input field, treats the space as a whitespace in the search term.
