### ISSUE TITLE
TextArea - cols and rows

### ISSUE THREAD

**Issue by alina-lapina** [statisticsnorway/ssb-component-library#181]
**Describe the bug**
TextArea component / 'ssb-text-area' style does not take into consideration 'cols' and 'rows' properties.

**To Reproduce**
When I code <TextArea cols={65} rows={4} /> or <div clasName='ssb-text-area'><textarea cols={65} rows={4}</>it shows as a 1 line full width. 

**Expected behavior**
I expect a textarea expand as described in w3c standard https://www.w3schools.com/tags/tag_textarea.asp

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Pro, Version 10.0.16299 Build 16299
 - Browser: Google Chrome 79.0.3945.130 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
-

**Additional context**
-

**Comment by ssb-cgn** [comment]
Vi oppretter en sak på dette :)

**Comment by ssb-cgn** [comment]
This is fixed in version 2.0.30
