### ISSUE TITLE
Security HIGH and MEDIUM severity: node-sass

### ISSUE THREAD

**Issue by alina-lapina** [statisticsnorway/ssb-component-library#206]
**Describe the bug**
Library node-sass is highly vulnerable:
![image](https://user-images.githubusercontent.com/21969896/83242694-1c99cb80-a19d-11ea-82ee-04cba0725066.png) as reported Snyk.

**Comment by ssb-cgn** [comment]
Ska sjekke det ut :)

**Comment by ssb-cgn** [comment]
updated node-sass to 4.14.1 in version 2.0.24 of ssb-component-library
