### ISSUE TITLE
Description correction

### ISSUE THREAD

**Issue by alina-lapina** [statisticsnorway/ssb-component-library#219]
**Describe the bug**
Usage example in the Guide is not syntactically correct (cannot be parsed)

**To Reproduce**
https://statisticsnorway.github.io/design-system/#/components/dropdown
Dropdown med forhåndsvalgt verdi
![image](https://user-images.githubusercontent.com/21969896/88789066-8a12aa00-d196-11ea-981a-e7444033f6a7.png)

**Expected behavior**
```
<Dropdown
	header="Menu header"
	selectedItem={{ title: 'Ocean', id: 'item3' }}
	items={items}
/>
```
NB: **double** curly brackets for selectedItem

**Additional context**
v2.0.28

**Comment by ssb-cgn** [comment]
This is fixed :)
