### ISSUE TITLE
Input labels have differen font-size and position relative to it's input box

### ISSUE THREAD

**Issue by alina-lapina** [statisticsnorway/ssb-component-library#229]
**Describe the bug**
Form labels have differen font- size and position relative to the input box. When used together in one form it creates a bit untidy look.

**Expected behavior**
Labels are expected to appear similar.

**Screenshots**
![image](https://user-images.githubusercontent.com/21969896/100543189-fab5fa00-324e-11eb-8982-a5c1049eeb20.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser Version 87.0.4280.66 (Official Build) (64-bit)
 - Version v2.0.36

**Smartphone (please complete the following information):**
Not tested yet.

**Comment by ssb-cgn** [comment]
Da er det opprettet en sak på dette :)

**Comment by ssb-cgn** [comment]
Denne er løst
