### ISSUE TITLE
Accordion: allow to provide a component, not a string

### ISSUE THREAD

**Issue by alina-lapina** [statisticsnorway/ssb-component-library#234]
**Is your feature request related to a problem? Please describe.**
There are two cases in my Klass project when an icon has to be shown in the Accordion header:
- alert along with the header text;
- spinner instead of a header text, while it's loading.
It causes an error.
![image](https://user-images.githubusercontent.com/21969896/101982706-1d480a00-3c76-11eb-85b1-4968a31f3515.png)
![image](https://user-images.githubusercontent.com/21969896/101982817-ce4ea480-3c76-11eb-9f14-7d1744675692.png)

**Describe the solution you'd like**
If Accordion could accept a component as a prop to a header, it would render without an error.

**Describe why this is useful for SSB**
Flexibility makes a component useful in different cases.

**Comment by ssb-cgn** [comment]
Har opprettet en sak på dette hos oss nå :)

**Comment by ssb-cgn** [comment]
Denne vil vi ikke prioritere å løse.
